#!/usr/bin/env python3
"""prune-site.py — remove published files whose (gitignored) source is gone.

Hakyll never deletes an output whose source has disappeared, and
tools/build-freshness.sh can only force a clean rebuild for deletions git
can see. Score pages, realizations and timing maps are gitignored
(content/music/*/scores/, regenerated by tools/music-import.py), so a
re-engrave with fewer pages, a re-import without --audio, or a movement
withheld again with `refresh --movements` left the old files in _site —
and `rsync --delete` kept them public until the weekly clean (audit M02).
For a withheld movement that defeats the point of withholding it.

Run after the last compile pass, before compression and signing:

    tools/prune-site.py _site

Each removed file is listed, together with any compression or signature
sidecar beside it. Nothing outside the trees below is touched.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# (published tree under _site, its source tree, the subdirectory of each
# work whose files are copied one to one from gitignored sources)
TREES = [("music", ROOT / "content" / "music", "scores")]
SIDECARS = (".br", ".gz", ".sig")


def prune(site: Path, trees=TREES) -> list[Path]:
    removed: list[Path] = []
    for published, source, sub in trees:
        base = site / published
        if not base.is_dir():
            continue
        for work in sorted(p for p in base.iterdir() if p.is_dir()):
            out_dir = work / sub
            if not out_dir.is_dir():
                continue
            for f in sorted(p for p in out_dir.rglob("*") if p.is_file()):
                rel = f.relative_to(base)
                name = rel.as_posix()
                for suffix in SIDECARS:
                    if name.endswith(suffix):
                        name = name[: -len(suffix)]
                        break
                if not (source / name).exists():
                    f.unlink()
                    removed.append(f)
    return removed


def main(argv: list[str]) -> int:
    if len(argv) != 1:
        print("usage: prune-site.py <site-dir>", file=sys.stderr)
        return 2
    site = Path(argv[0])
    if not site.is_dir():
        print(f"prune-site: {site} is not a directory", file=sys.stderr)
        return 2
    removed = prune(site)
    for f in removed:
        print(f"prune-site: removed {f.relative_to(site)} (its source is gone)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
